### ISSUE TITLE
Extract extreme values, e.g. from Heave

### ISSUE THREAD

**Issue by martin-loland-4ss** [4Subsea/waveresponse-python#41]
Would like to find extreme values on vessel response given:
- RAO
- weather

Ask Sveinung for more information.

**Comment by sveinung-eriksrud-4ss** [comment]
Use of spectral moments to fit the Rayleigh distribution as described by Ochi and calculate quantiles of the extreme value distribution. Must estimate Tz from spectral moments. 

https://www.orcina.com/wp-content/uploads/resources/validation/99-108-Extreme-wave-statistics.pdf

**Comment by ace-e4s** [comment]
Looks reasonably straight forward. We should move the `tz` property from `WaveSpectrum` class to `DirectioalSpectrum` class. Also, add a property for "spectral width" (often denoted `eps` in the literature).

For extreme value, we could add a `.extreme(t_total, alpha=0.9)` method to `DirectionalSpectrum`.

Easy peasy, lemon squeezy!

**Comment by heidi-holm-4ss** [comment]
https://4insight.atlassian.net/browse/DST-348

**Comment by vegard-solum-4ss** [comment]
We are working on this feature in this pull request: https://github.com/4Subsea/waveresponse-python/pull/45

**Comment by vegard-solum-4ss** [comment]
Now implemented and merged with main.
